# Use the Ubuntu base image
FROM ubuntu:22.04

ENV DIR=RealTimeSoftVoiceChanger 

# Set the working directory
WORKDIR /app

# Copy the TEST_Linux_MinGW_Cmake directory
COPY ./${DIR} /app/${DIR}

# Update the package list and install dependencies
RUN apt-get update && \
    apt-get install -y gpg wget build-essential

# # Install MinGW
# RUN apt-get update && \
#     apt-get install -y mingw-w64 && \
#     apt-get install -y g++-mingw-w64-i686 && \
#     apt-get install -y binutils-mingw-w64-x86-64 && \
#     apt-get install -y mingw-w64-common && \
#     apt-get install -y mingw-w64-x86-64-dev && \
#     apt-get install -y mingw-w64-tools && \
#     apt-get install -y gcc-mingw-w64-base && \
#     apt-get install -y gcc-mingw-w64-x86-64 && \
#     apt-get install -y g++-mingw-w64-x86-64 && \
#     apt-get install -y libsndfile1-dev

# Install
RUN apt-get update && \
    apt-get install -y autoconf automake libtool pkg-config build-essential g++

# Install sudo
RUN apt-get update && apt-get -y install sudo

# Install Git
RUN apt-get update && \
    apt-get install -y git

# Install CMake
RUN apt-get install -y cmake

# # Install PortAudio
# RUN apt-get update && \
#     cd ./${DIR}/environment && \
#     mkdir portaudio_build && \
#     cd portaudio_build && \
#     apt-get install -y git && \
#     git clone https://github.com/PortAudio/portaudio && \
#     cd portaudio && \
#     mkdir build && \
#     cd build && \
#     cmake -DCMAKE_INSTALL_PREFIX=/usr/x86_64-w64-mingw32 \
#         -DCMAKE_TOOLCHAIN_FILE=/app/${DIR}/toolchain.cmake \
#         -DCMAKE_BUILD_TYPE=Release \
#         -DBUILD_SHARED_LIBS=ON .. && \
#     make && \
#     make install

# # Install SoundTouch
# RUN apt-get update && \
#     cd ./${DIR}/environment && \
#     mkdir soundtouch_build && \
#     cd soundtouch_build && \
#     wget https://www.surina.net/soundtouch/soundtouch-2.3.0.tar.gz && \
#     tar zxvf soundtouch-2.3.0.tar.gz && \
#     cd soundtouch-2.3.0 && \
#     cmake -DCMAKE_INSTALL_PREFIX=/usr/x86_64-w64-mingw32 \
#         -DCMAKE_TOOLCHAIN_FILE=/app/${DIR}/toolchain.cmake \
#         -DCMAKE_BUILD_TYPE=Release \
#         -DBUILD_SHARED_LIBS=ON . && \
#     make && \
#     make install && \
#     ./bootstrap && \
#     ./configure --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/

# Set the entry point or CMD according to your needs
CMD ["/bin/bash"]